# Generated by Django 5.1.2 on 2024-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssales",
            name="quantity_purchased",
            field=models.IntegerField(),
        ),
    ]
