# Generated by Django 5.1.2 on 2024-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_productssales_quantity_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssales",
            name="quantity_purchased",
            field=models.PositiveIntegerField(),
        ),
    ]
